name: Docker Image CI

on:
  pull_request:
    types:
      - closed

    paths-ignore:
      - 'README.md'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Define the access that the GITHUB_TOKEN will permit
permissions: write-all

jobs:
  test-build:
    name: Test | Build a Docker Image
    environment: test
    runs-on: ubuntu-latest

    # run this job only when PR is approved
    if: github.event.pull_request.merged == true

    steps:
    - 
      name: Check out into Repo
      uses: actions/checkout@v4
    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  # This job build a docker images from the dockerfile in our repo
  # and push that docker image to Docker Hub. More inof here: 
  # https://github.com/marketplace/actions/build-and-push-docker-images
  build-deploy:
    name: Deploy 2 DockerHub
    environment: prod

    # This is the runner aka container/machine where 
    #our deployment pipeline is going to run.
    runs-on: ubuntu-latest

    # only deploy to prod when test was successful 
    needs: test-build
    
    steps:
      - 
        name: Check out into the repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # neisguy/nodejs-backend:tagname
          # dockerhub username / dockerhub reposiroty : the image tag
          tags: ${{ vars.DOCKERHUB_USERNAME }}/nodejs-backend:latest
